language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

env:
  - DJANGO_VERSION=1.11.5

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test-requirements.txt
  - python setup.py install

# command to run tests
script:
  - python manage.py test
