language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.11.5

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2; fi
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test-requirements.txt
  - python setup.py install

# command to run tests
script:
  - python manage.py test
